-- ═════════════════════════════════════════════════════════════════════════════
-- INCIDENT RECORD — DO NOT EDIT BELOW THIS LINE
-- ═════════════════════════════════════════════════════════════════════════════
--
-- This migration was generated by `prisma migrate dev --create-only` at
-- the start of Phase 7a, intended to be inspected and have its spurious
-- `DROP INDEX "KnowledgeChunk_embedding_hnsw"` line stripped BEFORE
-- application (per the standing rule in CLAUDE.md §6, "Generated SQL
-- inspection — standing rule for every new migration").
--
-- The migrate-dev process was Ctrl+C'd at the drift prompt as expected.
-- A subsequent `migrate dev` re-run, intended to re-generate the file
-- with the same name, ran its pre-flight pending-migration apply pass
-- against this on-disk file FIRST and applied it as-written — including
-- the DROP INDEX line — before generating an empty new migration.
--
-- The drop-then-restore sequence is now intentional history:
--   - This file dropped KnowledgeChunk_embedding_hnsw at apply-time
--     (recorded as finished in _prisma_migrations).
--   - The next migration,
--     20260429020000_phase7a_corrective_restore_hnsw_add_meta_indexes,
--     restores the index identically and adds the two partial unique
--     indexes the original 7a was meant to land.
--
-- The MESSENGER enum addition below was the only intended side effect
-- and is preserved by the corrective migration.
--
-- Recovery protocol added to CLAUDE.md §6 in 7g: never re-run
-- `migrate dev` after Ctrl+C without first inspecting and stripping
-- the on-disk migration file the killed run created. Use
-- `db:migrate:deploy` after correction; it skips the pre-flight
-- apply pass and applies only what's been corrected.
--
-- ═════════════════════════════════════════════════════════════════════════════

-- AlterEnum
ALTER TYPE "ChannelType" ADD VALUE 'MESSENGER';

-- DropIndex
DROP INDEX "KnowledgeChunk_embedding_hnsw";
