import "server-only";

import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";

/**
 * AES-256-GCM envelope for Live Data Source credentials. Plaintext only
 * ever materializes inside the adapter at the moment of authentication
 * (see src/server/integrations/odoo/client.ts) — never in logs, API
 * responses, error messages, or test fixtures.
 *
 * Wire format (base64): IV (12 bytes) ‖ authTag (16 bytes) ‖ ciphertext.
 * The IV is freshly random per call so two encryptions of the same
 * plaintext produce different ciphertexts (verified by crypto.test.ts).
 *
 * Key management: LIVE_DATA_ENCRYPTION_KEY is a 32-byte base64 string
 * generated by scripts/generate-encryption-key.ts. App fails fast at
 * call time if the env var is missing or wrong length. In production
 * the key MUST be in the deployment platform's secret manager (not
 * committed). Losing the key means losing access to every encrypted
 * credential — operators have to re-enter Odoo passwords per source.
 */

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12;
const AUTH_TAG_LENGTH = 16;
const KEY_LENGTH = 32;

function getEncryptionKey(): Buffer {
  const raw = process.env.LIVE_DATA_ENCRYPTION_KEY;
  if (!raw) {
    throw new Error(
      "LIVE_DATA_ENCRYPTION_KEY missing. Run: npx tsx scripts/generate-encryption-key.ts",
    );
  }
  const key = Buffer.from(raw, "base64");
  if (key.length !== KEY_LENGTH) {
    throw new Error(
      `LIVE_DATA_ENCRYPTION_KEY must be ${KEY_LENGTH} bytes (base64). Got ${key.length} bytes.`,
    );
  }
  return key;
}

export function encryptConfig(plaintext: string): string {
  const key = getEncryptionKey();
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const ciphertext = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  return Buffer.concat([iv, authTag, ciphertext]).toString("base64");
}

export function decryptConfig(blob: string): string {
  const key = getEncryptionKey();
  const buffer = Buffer.from(blob, "base64");
  if (buffer.length < IV_LENGTH + AUTH_TAG_LENGTH) {
    throw new Error("Encrypted blob too short — corrupt or wrong format");
  }
  const iv = buffer.subarray(0, IV_LENGTH);
  const authTag = buffer.subarray(IV_LENGTH, IV_LENGTH + AUTH_TAG_LENGTH);
  const ciphertext = buffer.subarray(IV_LENGTH + AUTH_TAG_LENGTH);
  const decipher = createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  return Buffer.concat([
    decipher.update(ciphertext),
    decipher.final(),
  ]).toString("utf8");
}
