import "server-only";
import type { SupportedReplyLanguage } from "./claude-client";

/**
 * Deterministic safe-fallback replies for the failure paths where the LLM
 * itself is the unreliable component:
 *
 *   - TOOL_REFUSAL: Claude returned end_turn with no tool_use block
 *     (forced tool-use refused). The orchestrator synthesizes a BrainResult
 *     using `getToolRefusalFallback(language)` for the reply text.
 *
 * These strings MUST NOT be generated by the LLM at request time — when
 * the LLM is the failure point, asking it to generate the apology is
 * exactly the wrong move. Hardcoded per language: FR / AR / EN / Darija
 * (Arabizi script — by far the most common Darija script in MENA SMB
 * customer messages; Arabic-script Darija customers tend to accept MSA
 * fallbacks gracefully).
 *
 * Phrasing is deliberately neutral and short: acknowledge the limit, offer
 * a human handoff, no fake apology that pretends a real reason. Operators
 * can edit Block A's escalation language but the fallbacks here are the
 * floor — what gets surfaced when even the model refuses to engage.
 */

const TOOL_REFUSAL_FALLBACKS: Record<SupportedReplyLanguage, string> = {
  en: "I can't help with that — let me connect you with our team.",
  fr: "Je ne peux pas vous répondre sur ce point — je vous mets en relation avec notre équipe.",
  ar: "آسف، لا أستطيع المساعدة في هذا الموضوع — سأقوم بتحويلك إلى أحد أعضاء فريقنا.",
  // Arabizi (Latin + numerals): the dominant Darija script in customer
  // messages. Customers writing in Arabic-script Darija get this same
  // text — a Darija reader recognizes either form.
  darija: "Smahli, ma nqdarch n3awnek f hadi — ghadi nwesslek 3la wa7ed men l-équipe dyalna.",
};

/**
 * Fallback reply when Claude refused to call the forced tool. Returns a
 * fixed string per language — never throws, always returns something.
 */
export function getToolRefusalFallback(language: SupportedReplyLanguage): string {
  return TOOL_REFUSAL_FALLBACKS[language];
}
